### ISSUE TITLE
Need french support

### ISSUE THREAD

**Issue by jlherondelle** [QQorp/QQat#1]
Je comprend pas l'anglais

**Comment by jlherondelle** [comment]
Can you traduce in france

**Comment by KevinBacas** [comment]
Bien sûr, je peux le traduire en Français. Je vais faire un Readme spécialement pour toi ! :smile:

**Comment by jlherondelle** [comment]
mci bcp, g 1 pe 2 mal ac lenglé

**Comment by LouisDelbosc** [comment]
Voilà, normalement j'ai traduit le README.md en français. Va voir le READMEfr.md.
Il se peut qu'il y ait encore des fautes de traductions et/ou de français, je te prie de me pardonner.
